### - PoE Leagues
GET https://api.pathofexile.com/leagues?type=main&realm=pc
User-Agent: PoE Filter Generator https://github.com/ajoscram/PoE-Filter-Generator/

### - PoE Ninja queries
@league = Sanctum
@item_type = UniqueFlask
@currency_type = Currency

### Currency or Frags
GET https://poe.ninja/api/data/currencyoverview?league={{league}}&type={{currency_type}}

### Items
GET https://poe.ninja/api/data/itemoverview?league={{league}}&type={{item_type}}

### - Wiki Cargo Queries
### Docs: https://www.poewiki.net/wiki/Special:CargoQuery
### Tables: https://www.poewiki.net/wiki/Special:CargoTables
@tables = mod_spawn_weights
@fields = _pageName, tag
@where =
@group_by = 
@order_by =
@join_on = 
@limit = 200

### Direct API Queries
GET https://www.poewiki.net/w/api.php?action=cargoquery&format=json&tables={{tables}}&fields={{fields}}&where={{where}}&group_by={{group_by}}&order_by={{order_by}}&join_on={{join_on}}&limit={{limit}}

### PHP Queries
GET https://www.poewiki.net/index.php?title=Special:CargoExport&format=json&tables={{tables}}&fields={{fields}}&where={{where}}&order+by={{order_by}}&join+on={{join_on}}&limit={{limit}}