### PoE Leagues
GET https://api.pathofexile.com/leagues?type=main&realm=pc
User-Agent: PoE Filter Generator https://github.com/ajoscram/PoE-Filter-Generator/

### PoE Ninja queries
@league = Necropolis
@item_type = Memory
@currency_type = Currency

#### Currency or Frags
GET https://poe.ninja/api/data/currencyoverview?league={{league}}&type={{currency_type}}

#### Items
GET https://poe.ninja/api/data/itemoverview?league={{league}}&type={{item_type}}

### RePoE Queries
#### Docs: https://github.com/brather1ng/RePoE/tree/master/RePoE/docs

#### Item classes
GET https://repoe-fork.github.io/item_classes.min.json

#### Item mods
GET https://repoe-fork.github.io/mods.min.json

#### Base items
GET https://repoe-fork.github.io/base_items.min.json

### Wiki Cargo Queries
#### Docs: https://www.poewiki.net/wiki/Special:CargoQuery
#### Tables: https://www.poewiki.net/wiki/Special:CargoTables
@tables = mod_spawn_weights
@fields = _pageName, tag
@where =
@group_by = 
@order_by =
@join_on = 
@limit = 200

#### Direct API Queries
GET https://www.poewiki.net/w/api.php?action=cargoquery&format=json&tables={{tables}}&fields={{fields}}&where={{where}}&group_by={{group_by}}&order_by={{order_by}}&join_on={{join_on}}&limit={{limit}}

#### PHP Queries
GET https://www.poewiki.net/index.php?title=Special:CargoExport&format=json&tables={{tables}}&fields={{fields}}&where={{where}}&order+by={{order_by}}&join+on={{join_on}}&limit={{limit}}

#### PFG Docs
@page = :help

GET https://raw.githubusercontent.com/wiki/ajoscram/PoE-Filter-Generator/{{page}}.md