# Operands
HIDE = "Hide"
SHOW = "Show"
MINIMAL = "Minimal"
CLASS = "Class"
BASE_TYPE = "BaseType"
LINKED_SOCKETS = "LinkedSockets"

BLOCK_STARTERS = [ HIDE, SHOW, MINIMAL ]

# Rules
COMMENT_START = '#'
RULE_SEPARATOR = '.'
RULE_START = COMMENT_START + RULE_SEPARATOR