# Operands
HIDE = "Hide"
SHOW = "Show"
MINIMAL = "Minimal"
CLASS = "Class"
BASE_TYPE = "BaseType"
LINKED_SOCKETS = "LinkedSockets"
REPLICA = "Replica"
DROP_LEVEL = "DropLevel"
ITEM_LEVEL = "ItemLevel"
AREA_LEVEL = "AreaLevel"
HAS_EXPLICIT_MOD = "HasExplicitMod"
BLOCK_STARTERS = [ HIDE, SHOW, MINIMAL ]

# Operators
GREATER_EQUALS = ">="
GREATER = ">"
LESS_EQUALS = "<="
LESS = "<"
CONTAINS = "="
EQUALS = "=="
NOT_CONTAINS = "!"
NOT_EQUALS = "!="

# Rules
COMMENT_START = '#'
RULE_SEPARATOR = '.'
RULE_START = COMMENT_START + RULE_SEPARATOR

# PFG
DEFAULT_WIKI_PAGE_NAME = "Usage"
HANDLER_START = RULE_SEPARATOR
COMMAND_START = ":"