# gh workflow run release
name: release
run-name: "${{ github.workflow }} by ${{ github.triggering_actor }}"

on: workflow_dispatch

jobs:
  release:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.12"

    - name: Install and test
      uses: ./.github/actions/install-and-test

    - name: Build pfg.exe and updater.exe
      shell: bash
      run: scripts/build.sh include-updater

    - name: Get release metadata
      id: metadata
      shell: bash
      run: |
        echo "VERSION=$(scripts/version.sh)" >> $GITHUB_OUTPUT
        scripts/notes.sh > notes.md

    - name: Create release
      uses: ncipollo/release-action@v1
      with:
        name: ${{ steps.metadata.outputs.VERSION }} PoE Filter Generator Update
        tag: ${{ steps.metadata.outputs.VERSION }}
        bodyFile: "notes.md"
        artifacts: "build/*.exe"