name: release
run-name: "${{ github.workflow }} on ${{ github.event_name }} by ${{ github.triggering_actor }}: \"${{ github.event.head_commit.message }}\""

on: push #workflow_dispatch

jobs:
  release:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3

    - name: Get release version
      id: version
      shell: bash
      run: echo "VERSION=$(scripts/version.sh)" >> "$GITHUB_OUTPUT"
    
    - name: Get release notes
      id: notes
      shell: bash
      run: |
        DELIMITER=$(dd if=/dev/urandom bs=15 count=1 status=none | base64)
        echo "NOTES<<$DELIMITER" >> "$GITHUB_OUTPUT"
        "$(scripts/notes.sh)" >> "$GITHUB_OUTPUT"
        echo "$DELIMITER" >> "GITHUB_OUTPUT"
    
    - name: Print notes and version
      shell: bash
      run: |
        echo ${{ steps.version.outputs.VERSION }}
        echo ${{ steps.notes.outputs.NOTES }}

    # - name: Create release
    #   uses: actions/create-release@v1
    #   env:
    #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    #   with: 
    #     tag_name: ${{ steps.version.outputs.VERSION }}
    #     release_name: ${{ steps.version.outputs.VERSION }} PoE Filter Generator Update
    #     body: ${{ steps.notes.outputs.NOTES }}