name: release

on: workflow_dispatch

jobs:
  test:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3

    - name: Get release version
      id: version
      shell: bash
      run: VERSION=$(scripts/version.sh) >> $GITHUB_OUTPUT
    
    - name: Get release notes
      id: notes
      shell: bash
      run: NOTES=$(scripts/notes.sh) >> $GITHUB_OUTPUT
    
    - name: Create release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with: 
        tag_name: ${{ steps.version.outputs.VERSION }}
        release_name: ${{ steps.version.outputs.VERSION }} PoE Filter Generator Update
        body: ${{ steps.notes.outputs.NOTES }}